#!/bin/sh
javac -classpath ../backflip-helper/javac -d javac -sourcepath source source/com/backflipsource/servlet/Compile.java
java -classpath javac:../backflip-helper/javac com.backflipsource.servlet.Compile
